apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: k8s-ci-cd-dev
namespace: app-dev
resources:
  - ../../base
commonLabels:
  environment: dev
patches:
  - path: patches/deployment.yaml
  - path: patches/ingress.yaml
  - path: patches/externalsecret.yaml
  - path: patches/serviceaccount.yaml
images:
  - name: app
    newName: ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/k8s-ci-cd-app
    newTag: latest-dev
